CREATE TABLE CLIENTES (
    CLI_ID           INTEGER        NOT NULL,
    CLI_NOME         VARCHAR(30)    NOT NULL,
    CLI_SALDO        DECIMAL(9,0)   NOT NULL,
    DT_ATUALIZACAO   DATE,
    PRIMARY KEY (CLI_ID)
);

CREATE TABLE TRANSACOES (
    TRX_ID           INTEGER        NOT NULL,
    CLI_ID           INTEGER        NOT NULL,
    TRX_TIPO         CHAR(1)        NOT NULL,
    TRX_VALOR        DECIMAL(9,0)   NOT NULL,
    DT_PROCESSAMENTO DATE,
    PRIMARY KEY (TRX_ID)
);

CREATE TABLE ERROS_PROCESSAMENTO (
    ID_ERRO          INTEGER GENERATED ALWAYS AS IDENTITY,
    CLI_ID           INTEGER,
    DESCRICAO_ERRO   VARCHAR(100),
    DT_OCORRENCIA    TIMESTAMP
);

CREATE INDEX IDX_TRX_CLI_ID
    ON TRANSACOES (CLI_ID);

CREATE INDEX IDX_ERR_CLI_ID
    ON ERROS_PROCESSAMENTO (CLI_ID);
    